---
title: "King County Housing Prices"
author: "Duncan McKinnon"
output: html_notebook
---

This project aims to explore data on housing prices in an effort to design a model for estimating pricing and other behaviors of the housing market, specifically within King County. 


```{r}
knitr::opts_chunk$set(message = F, warning = F, strip.white = F, tidy = T)

#install or load required packages into the workspace
package_list <- c('tidyverse', 'plotly','RColorBrewer','sqldf')
non_installed <- package_list[!(package_list %in% installed.packages()[,"Package"])]
if(length(non_installed)) install.packages(non_installed)
library('tidyverse')
library('plotly')
library('RColorBrewer')
library('sqldf')
```



```{r}
#load dataset from project folder
suppressWarnings({housing_data <- read.csv("kc_house_data.csv", stringsAsFactors = F)})


#remove unused columns and normalize the data
housing_data_rev <- housing_data[, 4:21]

for(i in 1:17)
{
  housing_data_rev[,i] <- housing_data_rev[,i]
}

housing_data_rev$price <- housing_data$price
```



```{r}
#collect a random sampling of the dataset ordered by price
sample_values <- sample(dim(housing_data)[1], 200)

housing_data_sample <- as.data.frame(housing_data_rev[sample_values,])

housing_data_sample <- sqldf("Select * 
                           From housing_data_sample
                           Order By price desc")

sqldf("Select price As Pricing, grade As Rating, sqft_lot As Sq_Footage, yr_built As Year_Built
       From housing_data_sample
       Limit 20")

```



```{r}
#Look at the distributions:
p1 <- plot_ly() %>% add_markers(name = "Pricing", x = 1:200, y = housing_data_sample$price) %>% layout(title = "King County Housing Feature Distributions")
p2 <- plot_ly() %>% add_markers(name = "Rating", x = 1:200, y = housing_data_sample$grade)
p3 <- plot_ly() %>% add_markers(name = "Sq. Footage", x = 1:200, y = housing_data_sample$sqft_lot)
p4 <- plot_ly() %>% add_markers(name = "Year Built", x = 1:200, y = housing_data_sample$yr_built)
subplot(p1, p2, p3, p4, nrows = 2)
```



```{r message = F, warning = F}
#normalize the data and split for training
housing_data_rev <- housing_data[, 4:21]

for(i in 1:17)
{
  housing_data_rev[,i] <- scale(housing_data_rev[,i])
}

housing_data_rev$price <- housing_data$price

sample_values <- sample(dim(housing_data)[1], 200)

housing_data_tools <- as.data.frame(housing_data_rev[sample_values,])

housing_data_tools <- sqldf("Select * 
                           From housing_data_tools
                           Order By price desc")

#test general linear model on relevant quantitative data
train_set_glm <- housing_data_tools[, !(colnames(housing_data_rev) %in% c("price", "yr_built", "yr_renovated", "lat", "long", "zipcode"))]
train_price <- housing_data_tools[, "price"]

glm_mod <- glm.fit(x = train_set_glm, y = train_price)

price_mod <- fitted(glm_mod)

price_est_plotly <- plot_ly() %>% 
  add_markers(name = "actual price", x = 1:length(train_price), y = train_price) %>%
  add_markers(name = "linear model est", x = 1:length(price_mod), y = price_mod) %>%
  add_lines(name = "magnitude difference", x = 1:length(train_price), y = price_mod - train_price) %>%
  layout(title = "Attempted Linear Regression Model </br> 
         for Pricing Homes in King County </br>")

price_est_plotly
```

